# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2a7JxLUPZ0pwytyshLlbWCS22uqSXGT

Studi Kasus 1 — Analisis Data dan AI
Tujuan

Menganalisis hasil deteksi sampah plastik berdasarkan jumlah deteksi benar, objek yang terlewat (False Negative), dan deteksi keliru (False Positive). Program akan menghitung metrik evaluasi dan menampilkan grafik perbandingan kondisi latar belakang.

Kode 1. Membuat data contoh

Buat satu sel kode baru dan jalankan. Data ini merupakan data simulasi untuk empat kondisi latar belakang pesisir.
"""

import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

# Data simulasi, bukan hasil pengamatan lapangan
data = {
    "Kondisi_Latar": [
        "Relatif Bersih",
        "Pasir Kering",
        "Pasir Basah",
        "Sampah Organik"
    ],
    "TP": [90, 78, 72, 65],
    "FN": [10, 22, 28, 35],
    "FP": [5, 12, 15, 20],
    "TN": [95, 88, 85, 80]
}

df = pd.DataFrame(data)

print("DATA SIMULASI HASIL DETEKSI SAMPAH PLASTIK")
display(df)

"""Keterangan:

TP (True Positive): sampah plastik berhasil dideteksi dengan benar.

FN (False Negative): sampah plastik sebenarnya ada, tetapi tidak terdeteksi.

FP (False Positive): objek yang bukan sampah plastik keliru terdeteksi sebagai sampah plastik.

TN (True Negative): objek atau area yang bukan sampah plastik dikenali dengan benar sebagai bukan target.

Kode 2. Menghitung metrik evaluasi
"""

import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

# Data simulasi, bukan hasil pengamatan lapangan
data = {
    "Kondisi_Latar": [
        "Relatif Bersih",
        "Pasir Kering",
        "Pasir Basah",
        "Sampah Organik"
    ],
    "TP": [90, 78, 72, 65],
    "FN": [10, 22, 28, 35],
    "FP": [5, 12, 15, 20],
    "TN": [95, 88, 85, 80]
}

df = pd.DataFrame(data)

print("DATA SIMULASI HASIL DETEKSI SAMPAH PLASTIK")
display(df)

"""Kode 3. Membuat grafik perbandingan"""

import matplotlib.pyplot as plt

# Pastikan kolom yang dibutuhkan tersedia
metrik_grafik = ["FNR (%)", "FPR (%)", "Recall (%)"]

kolom_tidak_ada = [
    kolom for kolom in metrik_grafik
    if kolom not in df.columns
]

if kolom_tidak_ada:
    print("Kolom berikut belum tersedia:", kolom_tidak_ada)
    print("Kolom yang tersedia:", df.columns.tolist())
else:
    grafik = df.set_index("Kondisi_Latar")[metrik_grafik]

    ax = grafik.plot(
        kind="bar",
        figsize=(10, 6),
        width=0.75
    )

    ax.set_title("Evaluasi Deteksi Sampah Plastik")
    ax.set_xlabel("Kondisi Latar Belakang")
    ax.set_ylabel("Nilai (%)")
    ax.set_ylim(0, 100)
    ax.tick_params(axis="x", rotation=15)

    plt.tight_layout()
    plt.show()

"""Kode 4. Menyimpan hasil untuk GitHub"""

nama_file = "hasil_analisis_deteksi.csv"

df.to_csv(nama_file, index=False)

print(f"Hasil analisis berhasil disimpan ke: {nama_file}")

from google.colab import files
files.download(nama_file)

"""Interpretasi hasil

Berdasarkan data simulasi di atas, kondisi latar belakang dengan sampah organik memiliki FN lebih tinggi daripada kondisi relatif bersih. Ini menggambarkan contoh bagaimana latar yang lebih kompleks dapat berkaitan dengan meningkatnya objek yang terlewat.

Penting: kesimpulan tersebut hanya berlaku pada data simulasi ini. Untuk menyatakan bahwa latar tertentu benar-benar menyebabkan penurunan kinerja YOLOv8, kamu perlu menguji model dengan data citra dan anotasi aktual.
"""