# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqQb8E27NbhBHhOu8Q4asfAmI9dn6KC0

Studi Kasus 2 — High Performance Computing (HPC)
Tujuan

Memproses banyak gambar menggunakan model YOLOv8 secara berkelompok (batch processing), menyimpan hasil deteksi, dan mencatat waktu pemrosesan. Ini merupakan contoh penerapan komputasi untuk membantu analisis masalah lingkungan.

Google Colab digunakan sebagai lingkungan demonstrasi. Menjalankan kode di Colab tidak berarti kamu sedang menggunakan klaster HPC sungguhan. Bagian HPC akan diperkenalkan melalui contoh skrip SLURM yang bisa disesuaikan untuk klaster yang mendukungnya.

Kode 1. Instalasi YOLOv8
"""

!pip -q install ultralytics pandas

"""Kode 2. Mengunggah gambar

Siapkan beberapa gambar sampah plastik, misalnya gambar botol plastik, kantong plastik, dan kemasan plastik di pantai. Kemudian jalankan:
"""

from google.colab import files
import os
import shutil

uploaded = files.upload()

folder_gambar = "/content/gambar_pesisir"
os.makedirs(folder_gambar, exist_ok=True)

ekstensi_valid = (".jpg", ".jpeg", ".png", ".bmp", ".webp")

jumlah_gambar = 0

for nama_file in uploaded.keys():
    if nama_file.lower().endswith(ekstensi_valid):
        shutil.move(
            nama_file,
            os.path.join(folder_gambar, os.path.basename(nama_file))
        )
        jumlah_gambar += 1

print(f"Jumlah gambar yang siap diproses: {jumlah_gambar}")
print(f"Lokasi gambar: {folder_gambar}")

"""Kode 3. Menjalankan deteksi YOLOv8 pada banyak gambar"""

from ultralytics import YOLO
from pathlib import Path
import pandas as pd
import time

# Model pralatih YOLOv8n akan diunduh otomatis jika belum tersedia.
model = YOLO("yolov8n.pt")

folder_input = Path("/content/gambar_pesisir")
folder_output = Path("/content/hasil_deteksi")
folder_output.mkdir(parents=True, exist_ok=True)

daftar_gambar = [
    p for p in folder_input.iterdir()
    if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
]

if not daftar_gambar:
    raise ValueError(
        "Tidak ada gambar. Unggah gambar terlebih dahulu pada Kode 2."
    )

hasil = []
waktu_mulai = time.perf_counter()

for gambar in daftar_gambar:
    mulai_gambar = time.perf_counter()

    prediksi = model.predict(
        source=str(gambar),
        conf=0.25,
        save=True,
        project=str(folder_output),
        name="prediksi",
        exist_ok=True,
        verbose=False
    )[0]

    durasi = time.perf_counter() - mulai_gambar

    # Jumlah seluruh prediksi dari semua kelas
    jumlah_prediksi = len(prediksi.boxes)

    # Nama kelas berdasarkan hasil prediksi
    nama_kelas = []
    for kelas_id in prediksi.boxes.cls.tolist():
        nama_kelas.append(model.names[int(kelas_id)])

    hasil.append({
        "Nama_Gambar": gambar.name,
        "Jumlah_Prediksi": jumlah_prediksi,
        "Kelas_Terdeteksi": ", ".join(sorted(set(nama_kelas))),
        "Waktu_Pemrosesan_Detik": round(durasi, 4)
    })

total_waktu = time.perf_counter() - waktu_mulai
df_hasil = pd.DataFrame(hasil)

print(f"Jumlah gambar diproses: {len(df_hasil)}")
print(f"Total waktu pemrosesan: {total_waktu:.2f} detik")
display(df_hasil)

"""Catatan: yolov8n.pt merupakan model deteksi objek pralatih umum. Model ini belum tentu dapat mendeteksi semua jenis sampah plastik dengan baik. Untuk deteksi yang secara khusus ditujukan pada sampah plastik, gunakan model yang telah dilatih atau disesuaikan dengan dataset sampah plastik.

Kode 4. Menyimpan laporan pemrosesan
"""

file_laporan = "/content/laporan_batch_yolov8.csv"
df_hasil.to_csv(file_laporan, index=False)

print("Laporan pemrosesan berhasil disimpan.")

from google.colab import files
files.download(file_laporan)

"""Gambar hasil prediksi disimpan pada direktori /content/hasil_deteksi/prediksi/. Untuk mengunduh semua gambar hasil prediksi sekaligus, jalankan:"""

import shutil
from google.colab import files

folder_hasil = "/content/hasil_deteksi/prediksi"
file_zip = shutil.make_archive(
    "/content/hasil_prediksi_yolov8",
    "zip",
    folder_hasil
)

files.download(file_zip)

"""Kode 5. Contoh konfigurasi pekerjaan HPC menggunakan SLURM

Materi kedua membahas pemanfaatan infrastruktur komputasi berkinerja tinggi. Pada klaster HPC yang menggunakan SLURM, kamu dapat menyiapkan berkas slurm_job.sh seperti berikut.


"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# #!/bin/bash
# #SBATCH --job-name=deteksi-sampah
# #SBATCH --output=hasil-%j.out
# #SBATCH --error=hasil-%j.err
# #SBATCH --time=00:30:00
# #SBATCH --cpus-per-task=4
# #SBATCH --mem=8G
# 
# # Aktifkan lingkungan Python sesuai konfigurasi klaster
# # Contoh jika menggunakan virtual environment:
# source .venv/bin/activate
# 
# echo "Memulai pemrosesan citra YOLOv8"
# python batch_inference.py
# echo "Pemrosesan selesai"

"""Karena menggunakan Google Colab, agar bisa digunakan di klaster HPC, perlu menyiapkan lingkungan Python, berkas batch_inference.py, model YOLOv8, data gambar, dan menyesuaikan konfigurasi sumber daya sesuai fasilitas klaster.

"""